# Generated by Django 6.0.6 on 2026-07-09 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_descripcionestudiante_tipoestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tipoestudiante',
            name='estudiante',
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='administrativo.estudiante')),
                ('tipo_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='administrativo.tipodireccion')),
            ],
        ),
        migrations.DeleteModel(
            name='DescripcionEstudiante',
        ),
        migrations.DeleteModel(
            name='TipoEstudiante',
        ),
    ]
